version: "3.9"

services:
  backend:
    build:
      context: ./Backend
    volumes:
      - ./Backend/taroproject:/app/taroproject
      - ./Backend/taroproject/media:/app/taroproject/media
    networks:
      - app-network

  frontend:
    build:
      context: ./Frontend
    volumes:
      - ./Frontend/vue-taro:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
