version: "3.8"

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./Backend/taroproject:/app
      - ./Backend/taroproject/media:/app/media
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    volumes:
      - ./Frontend/vue-taro:/app

    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
