# Generated by Django 5.2.6 on 2025-10-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaroCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='photo')),
                ('name', models.CharField(max_length=255)),
                ('descr_text', models.TextField()),
                ('love_text', models.TextField()),
                ('work_text', models.TextField()),
                ('day_text', models.TextField()),
                ('advice_text', models.TextField()),
                ('yesno_text', models.TextField()),
            ],
        ),
    ]
