# Generated by Django 5.2.6 on 2025-10-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taroapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarocard',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
